# Generated by Django 2.1.5 on 2019-07-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_id', models.IntegerField()),
                ('event_date', models.CharField(max_length=250)),
                ('season_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=100)),
                ('league_id', models.IntegerField()),
                ('sport', models.CharField(max_length=100)),
                ('alt_league_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_id', models.IntegerField()),
                ('birthday', models.DateField()),
                ('position', models.CharField(max_length=30)),
                ('sport', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_id', models.IntegerField()),
                ('short_name', models.CharField(max_length=50)),
                ('alt_team_name', models.CharField(max_length=100)),
                ('team_league_id', models.IntegerField()),
            ],
        ),
    ]
