# Generated by Django 2.1.5 on 2019-07-23 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_db', '0003_auto_20190705_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sports_db.Leagues'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='short_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
