# Generated by Django 2.1.5 on 2019-07-23 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_db', '0004_auto_20190723_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='current_id',
            field=models.IntegerField(default=59),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='current_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sports_db.Teams'),
        ),
    ]
