# Generated by Django 2.1.5 on 2019-07-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_db', '0005_auto_20190723_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
