# Generated by Django 2.1.5 on 2019-07-27 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_db', '0006_auto_20190727_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.IntegerField()),
                ('league', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sports_db.Leagues')),
            ],
        ),
    ]
