# Generated by Django 2.1.5 on 2019-07-27 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_db', '0007_seasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='season_id',
        ),
        migrations.AddField(
            model_name='events',
            name='away_score',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='events',
            name='away_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='away', to='sports_db.Teams'),
        ),
        migrations.AddField(
            model_name='events',
            name='event_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='events',
            name='home_score',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='events',
            name='home_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='sports_db.Teams'),
        ),
        migrations.AddField(
            model_name='events',
            name='result',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='sports_db.Teams'),
        ),
        migrations.AddField(
            model_name='events',
            name='season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sports_db.Seasons'),
        ),
        migrations.AddField(
            model_name='events',
            name='sport',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(),
        ),
    ]
